Sources/X509/OCSP/OCSPPolicy.swift
Motivation:
Swift CI disables implicit concurrency, so build fails without the import.
Modification:
Add explicit import for `_Concurrency`.
=> Explicitly import _Concurrency

CMakeLists.txt, Sources/X509/CMakeLists.txt
When building against a build tree artifact for Foundation, we need to add the build tree artifacts of dispatch as that is an exposed dependency for Foundation.
=> Fix CMake build

Sources/X509/Verifier/CertificateStore.swift, Sources/X509/Verifier/Verifier.swift, Tests/X509Tests/VerifierTests.swift
In some cases, we will have the leaf certificate in the trust root store. In this case, we can immediately pass that on to policy verification.
=> Handle leaves as trust roots

Sources/X509/CMakeLists.txt, Sources/X509/CertificatePublicKey.swift, Sources/X509/CryptographicMessageSyntax/CMSContentInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSEncapsulatedContentInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSIssuerAndSerialNumber.swift, Sources/X509/CryptographicMessageSyntax/CMSOperations.swift, Sources/X509/CryptographicMessageSyntax/CMSSignedData.swift, Sources/X509/CryptographicMessageSyntax/CMSSignerIdentifier.swift, Sources/X509/CryptographicMessageSyntax/CMSSignerInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSVersion.swift, Sources/X509/Signature.swift, Tests/X509Tests/CMSTests.swift
This patch adds support for basic CMS operations. We aren't sure that the API surface here is right, so for now we're going to provide this under an SPI guard so that we can make any amendments we might need.
=> CMS Signing support

Sources/X509/CMakeLists.txt, Sources/X509/Verifier/RFC5280/ExpiryPolicy.swift, Sources/X509/Verifier/RFC5280/RFC5280Policy.swift, Tests/X509Tests/RFC5280PolicyTests.swift
This is the first of a series of PRs that adds support for RFC 5280 policies as a single verifier policy. For now we take the low hanging fruit, expiry.
=> Add initial RFC5280 policy.

Package.swift, Sources/X509/Certificate.swift, Tests/X509Tests/CertificateDERTests.swift
When we decode a certificate, we produce an in-memory representation. This representation is something we are capable of encoding. If we re-encode that directly, we can produce an output that is different to the one we injested. This happens when there are objects that can be canonicalised, such as replacing an explicit ASN1 NULL with an absent field where both are considered equivalent.
This patch rewrites the code to ensure that we preserve the bytes of the certificate that we deserialized. This allows us to write them back unchanged, ensuring that certificates can round-trip through this library without modification.
A side-effect of this change is that we need to essentially encode the certificate on construction whenever we build them in memory. That's not a big deal, but it is a bit …
=> Avoid re-serializing certificates

Sources/X509/CMakeLists.txt, Sources/X509/Verifier/RFC5280/BasicConstraintsPolicy.swift, Sources/X509/Verifier/RFC5280/RFC5280Policy.swift, Tests/X509Tests/RFC5280PolicyTests.swift
This patch adds support for enforcing BasicConstraints in the RFC 5280 policy.
=> Add BasicConstraints enforcement to RF5280Policy

Package.swift, Sources/X509/CMakeLists.txt, Sources/X509/CertificatePublicKey.swift, Sources/X509/X509BaseTypes/RSAPKCS1PublicKey.swift, Tests/X509Tests/CertificateDERTests.swift
This updates Swift Crypto to 2.4.0 and fixes RSA key serialization on all platforms. It also adds a defensive check that we only accept appropriately-formatted RSA keys, and some regression tests.
=> Update Swift Crypto and fix RSA keys

Sources/X509/CertificateSerialNumber.swift, Tests/X509Tests/CertificateTests.swift
`Certificate.SerialNumber.init()` could produce a number where the first byte(s) could be zero(s). We strip them during encoding and will not and cannot reconstruct them after decoding. Therefore a serial number might no longer be equal to itself after a de/serialisation roundtrip. We have observed this behaviour to cause problems in the OCSP test suite with random test failures. This PR fixes it by dropping leading zeros.
=> Fix `Certificate.SerialNumber.init()`

Sources/X509/Verifier/RFC5280/DNSNames.swift, Tests/X509Tests/DNSNamesTests.swift
We incorrectly considered a trailing period to be a match-all clause. It's not. Make the code a little less clever to compensate.
=> Improve our handling of trailing periods.

Sources/X509/CMakeLists.txt, Sources/X509/Verifier/RFC5280/URIConstraints.swift, Tests/X509Tests/DNSNamesTests.swift
This is the last of the major constraint types we intend to support initially in name constraints. Mostly URIs leverage the domain name support, but we do have a need to parse URIs in order to extract their host component.
=> Add support for name constraints on URIs

Sources/X509/Verifier/RFC5280/NameConstraintsPolicy.swift, Sources/X509/Verifier/RFC5280/RFC5280Policy.swift, Tests/X509Tests/DNSNamesTests.swift, Tests/X509Tests/IPAddressTests.swift, Tests/X509Tests/NameConstraintsTests.swift, Tests/X509Tests/RFC5280PolicyTests.swift
This patch ties together the various checks we have already written into a single NameConstraintsPolicy, and attaches it to the RFC5280Policy. This includes defining the logic for traversing names, as well as for managing the excluded and permitted subtrees.
Unfortunately, this patch is giant. I wish I could do more about it, but fundamentally the majority of the code it adds is tests, and those tests are all necessary.
=> Produce functional NameConstraints

Sources/X509/OCSP/OCSPPolicy.swift, Sources/X509/Verifier/RFC5280/BasicConstraintsPolicy.swift, Sources/X509/Verifier/RFC5280/ExpiryPolicy.swift, Sources/X509/Verifier/RFC5280/NameConstraintsPolicy.swift, Sources/X509/Verifier/RFC5280/RFC5280Policy.swift, Sources/X509/Verifier/Verifier.swift, Sources/X509/Verifier/VerifierPolicy.swift, Tests/X509Tests/CMSTests.swift, Tests/X509Tests/RFC5280PolicyTests.swift, Tests/X509Tests/VerifierTests.swift
We are required to ensure that we do not validate chains that contain certificates with extensions marked critical that we do not understand. Because we allow pluggable policies which can handle arbitrary extensions, we need a way to ask verifier policy objects what extensions they can handle.
This patch adds support for policies to express that set, as well as for the verifier to ensure that certificates that have critical extensions we cannot understand are not used for chain building. This is integrated early into chain building to reject unsatisfiable chains, and works transparently.
This PR also updates the tests to meet this new standard, including applying the RFC 5280 policy liberally throughout the test suite.
=> Add support for policing critical extensions

Sources/X509/CMakeLists.txt, Sources/X509/Digests.swift, Sources/X509/Signature.swift, Sources/X509/X509BaseTypes/ECDSASignature.swift, Tests/X509Tests/CertificateDERTests.swift, Tests/X509Tests/SignatureTests.swift
This patch modifies the ECDSA signature representation internally to avoid eagerly creating the Crypto type. This is necessary because we can't actually know what key created the signature when we parse it. As a result we have to defer actually doing that until we actually get a key type, at which point we can create the underlying key type.
This is a bit less efficient for us overall, but it solves a long-tail problem in the WebPKI that is more likely to increase in frequency over time.
=> Tweak the ECDSA signature representation

Sources/X509/Verifier/RFC5280/RFC5280Policy.swift, Tests/X509Tests/RFC5280PolicyTests.swift
In general, disabling expiry checking is not a useful thing to do: it weakens security posture for no reason. In some testing use-cases or unusual product cases, however, it's valuable to do this. This patch adds support for ripping out expiry checking.
=> Add SPI support for disabling expiry checking in RFC5280Policy.

Sources/X509/Verifier/RFC5280/BasicConstraintsPolicy.swift, Tests/X509Tests/RFC5280PolicyTests.swift
Our current basic constraints checking policy requires the presence of the basic constraints extension to be a CA. That's too aggressive in the face of the ongoing persistence of v1 certs, both in the root store and in the wider ecosystem of devices. We can safely tolerate v1 certificates in almost all cases.
=> Tolerate v1 certs without basic constraints

Sources/X509/CertificatePrivateKey.swift, Sources/X509/Digests.swift, Tests/X509Tests/SignatureTests.swift
In some PKI applications private keys should be kept in the most secure manner possible.  The SecureEnclave provides the most secure repository and signing capabilities on Apple hardware. These changes allow applications to use SecureEnclave managed P256 private keys which can be referenced in a keychain while the cryptographic material and signing operations never leave the SecureEnclave.
The following key initializer is added to the api. Certificate.PrivateKey(SecureEnclave.P256.Signing.PrivateKey())
Issue: https://github.com/apple/swift-certificates/issues/51
=> Add support for using SecureEnclave.P256

Sources/X509/CertificatePublicKey.swift, Tests/X509Tests/CertificateTests.swift
In many circumstances it may be useful to extract the underlying public key from a Certificate.PublicKey. This patch adds support for optionally unwrapping the key into the various base types.
=> Add support for unwrapping public keys.

Sources/X509/OCSP/OCSPPolicy.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift
Soft failure mode allows to only trust OCSP responses once the responders certificate is fully verified. If the OCSP fails at any other step e.g. the request could not complete or decoding failed we still meet the OCSP policy in soft failure mode. This should generally be the default unless otherwise required.
=> OCSP soft failure mode

Sources/X509/OCSP/OCSPPolicy.swift
The latest nightly compiler rightly complains about a sendability violation. We capture `OCSPVerifierPolicy` in a `Sendable` closure but `OCSPVerifierPolicy` isn't `Sendable`. We don't want to make `OCSPVerifierPolicy` publicly `Sendable`. Therefore we need to extract all the state we want to capture in a separate type, now called `Storage`,  which we can then mark `Sendable`.
=> Fix `Sendable` warning in `OCSPVerifierPolicy. self.chainMeetsPolicyRequirementsWithoutDeadline`

Sources/X509/CMakeLists.txt, Sources/X509/CryptographicMessageSyntax/CMSContentInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSEncapsulatedContentInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSIssuerAndSerialNumber.swift, Sources/X509/CryptographicMessageSyntax/CMSOperations.swift, Sources/X509/CryptographicMessageSyntax/CMSSignature.swift, Sources/X509/CryptographicMessageSyntax/CMSSignedData.swift, Sources/X509/CryptographicMessageSyntax/CMSSignerIdentifier.swift, Sources/X509/CryptographicMessageSyntax/CMSSignerInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSVersion.swift, Tests/X509Tests/CMSTests.swift
There are some use-cases where interrogating the structure of a CMS signature is necessary. This patch adds an SPI for looking at a CMS signature.
As with the rest of our CMS operations, we're not willing to commit to an API shape yet, so this patch doesn't provide one. Instead, users need to opt-in to using the unstable API.
=> Expose a CMSSignature type

CMakeLists.txt, Package.swift, Sources/X509/CertificatePrivateKey.swift, Sources/X509/Digests.swift
Motivation:
macOS CMake build is failing with error:
```
/Users/ec2-user/jenkins/workspace/swift-package-manager-PR-macos-smoke-test/branch-main/swift-certificates/Sources/X509/CertificatePrivateKey.swift:158:32: error: cannot find type 'SecureEnclave' in scope
case secureEnclaveP256(SecureEnclave.P256.Signing.PrivateKey)
^~~~~~~~~~~~~
ninja: build stopped: subcommand failed.
```
https://ci.swift.org/job/swift-package-manager-PR-macos-smoke-test/2207/console
Modifications:
Introduce compiler directive `INCLUDE_SECURE_ENCLAVE_SUPPORT` to control when to include Secure Enclave related code. It is set in SwiftPM build (`Package.swift`) but not CMake.
=> Exclude Secure Enclave related code from CMake build

CMakeLists.txt, Package.swift, Sources/X509/CertificatePrivateKey.swift, Sources/X509/Digests.swift
Motivation:
https://github.com/apple/swift-certificates/pull/67 introduced a temporary workaround to unblock cmake build on macOS, but we have a proper fix now (https://github.com/apple/swift-crypto/pull/177).
Modifications:
- Revert https://github.com/apple/swift-certificates/pull/67
- Take new version of `swift-crypto` containing https://github.com/apple/swift-crypto/pull/177
=> Proper fix for 'SecureEnclave' issue in cmake build

README.md
Minor cleanup in the `upToNextMinor` code in the README.
=> Clean up the upToNextMinor

Sources/X509/Docs.docc/Creating Certificates.md
`name` doesn't exist in this context and probably refers to `subjectName` and `issuerName`
=> Fix wrong variable in documentation

Sources/X509/Verifier/RFC5280/URIConstraints.swift
`CoreFoundation` is not available on all platforms.  It never was meant to be available on Linux, but was accidentally pushed into the release and is now stuck.  Windows intentionally did not make this module visible.  With the future work with the Foundation rewrite `CoreFoundation` will disappear in more locations.
Windows does not support `inet_pton` except unless the string is explicitly ANSI and not UTF-8.  We must use the proper spelling of `InetPtonW` which takes a UTF-16 string.
The import of `CoreFoundation` was more for the dependency on the C library as a side-effect.  On Windows, the networking functions are provided by a separate user space library rather than the C library. This is now highlighted in the imports.
=> X509: make the code more portable

Sources/X509/Docs.docc/Creating Certificates.md
In a certificate chain, the child certificate's issuer is the parent certificate's subject.
Modifications:
Replaced ``Certificate/issuer`` with ``Certificate/subject`` to correct the meaning.
=> Fixed referenced property name in documentation

Sources/X509/Extensions.swift, Sources/X509/ExtensionsBuilder.swift, Tests/X509Tests/ExtensionBuilderTests.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift
We currently crash if `Extension` serialization fails but we should throw an error instead.
All `@resultBuilder` `build*` methods do not support throwing. We therefore need to delay throwing until the very end. The `@resultBuilder` final result type is now no longer `Certificate.Extensions` but `Result<Certificate.Extensions, any Error>` which allows us to forward the error. 
We throw the first serialization error instead of crashing. Note that we still serialize all `Extension`s but only preserve the error of the first failure.
=> Gracefully fail `Extension` serialization

Package.swift, Sources/X509/Verifier/RFC5280/ExpiryPolicy.swift, Sources/X509/X509BaseTypes/Time.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift, Tests/X509Tests/OCSPTests.swift
Currently, certificate verification is serverely bottlenecked on expiry checking. This bottleneck is almost entirely caused by converting Time objects into Date objects via DateComponents.
We can reduce the cost of this by doing fewer transformations. Instead of converting all the Time objects to Dates, we can convert a Date to a GeneralizedTime and then do all comparisons in GeneralizedTime space.
This vastly reduces the cost of cert validation.
=> Make expiry checking cheaper.

NOTICE.txt, Sources/X509/CMakeLists.txt, Sources/X509/Certificate.swift, Sources/X509/OCSP/OCSPPolicy.swift, Sources/X509/X509BaseTypes/Time.swift, Sources/X509/X509BaseTypes/TimeCalculations.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift, Tests/X509Tests/TimeTests.swift
Translating between Date and Time is expensive when we use DateComponents, because we jump through ICU unnecessarily. We can move over to standard UTC date math instead, which makes this process vastly cheaper.
=> Make constructing Dates cheaper

Sources/X509/Certificate.swift
The "from parts" Certificate constructor has existed for a while. As noted in the docstring, it was originally added for testing and validation purposes. However, it's not very useful for that purpose.
For one thing, many of the constitutuent parts are not actually directly constructible. For example, one cannot create a Signature type directly.
For another thing, invalid Certificate handling tests probably want to be able to construct Certificates that are invalid in a number of interesting ways, and so will want to use the DER representation to do so.
As a result, this intializer is not broadly useful: even this library doesn't use it for testing. Let's remove it.
=> Remove the "from parts" Certificate constructor.

Sources/X509/Signature.swift
This patch removes a TODO requesting validation of an RSA signature, which we cannot do.
=> Remove unnecessary TODO

Sources/X509/RelativeDistinguishedName.swift, Tests/X509Tests/DistinguishedNameTests.swift
and remove unnecessary TODO as discussed in https://github.com/apple/swift-certificates/pull/91#issuecomment-1573871378
=> Implement remove for `RelativeDistinguishedName`

Sources/X509/CertificatePublicKey.swift, Sources/X509/X509BaseTypes/AlgorithmIdentifier.swift
RSA PSS isn't really deployed in the WebPKI, and with the recent interest in post-quantum crypto it seems unlikely a new RSA padding mode will be specified. Let's not allude to trying to support it.
=> We aren't supporting PSS for now.

Sources/X509/Extension Types/ExtendedKeyUsage.swift, Sources/X509/Extensions.swift, Tests/X509Tests/ExtendedKeyUsageTests.swift, Tests/X509Tests/ExtensionBuilderTests.swift
When decoding a certificate we make sure that `ExtendedKeyUsage` and `Certificate.Extensions` only contain unique elements.
In the real world those collections are fairly small and we therefore use a linear scan to check for duplicates and fail decoding if we detect a duplicate.
However, a bad actor could increase the number of elements to an arbitrary number which will increase our decoding time exponentially.
Limit the number of elements we accept to 16 before we do the uniqueness check
We safely fail decoding for unreasonable large number of elements.
Note that if we encounter a real world use case for more elements we can also switch to hash based uniqueness check and support more elements safely.
=> Limit the number elements in `Extensions` and `ExtendedKeyUsage`

Sources/X509/Extension Types/NameConstraints.swift, Tests/X509Tests/NameConstraintsTests.swift
We want to support fine grained mutations of `NameConstraints`. In addition, the properties of it should only be views into the underlying storage to eliminate allocations costs for inspection `NameConstraints` properties.
- properties are now lazy views into the underlying storage
- setters for all properties are implemented
Mutating `NameConstraints` is now possible and getting the properties is lazy.
=> Implement property setters of `NameConstraints` 

IntegrationTests/tests_01_allocation_counters/test_01_resources/test_tiny_array_cow_append_contents_of.swift, IntegrationTests/tests_01_allocation_counters/test_01_resources/test_tiny_array_non_allocating_operations.swift, Package.swift, Sources/X509/CMakeLists.txt, Sources/X509/TinyArray.swift, Sources/_CertificateInternals/CMakeLists.txt, Sources/_CertificateInternals/_TinyArray.swift, Tests/CertificateInternalsTests/TinyArrayTests.swift, Tests/X509Tests/TinyArrayTests.swift, docker/docker-compose.2204.57.yaml, docker/docker-compose.2204.58.yaml, docker/docker-compose.2204.59.yaml, docker/docker-compose.2204.main.yaml, scripts/update_cmakelists.sh
We want to improve allocations for a couple of collections that are only ever expected to store a single element. However, in rare cases they might store multiple elements so they still need to support that.
=> Implement TinyArray

Sources/X509/Verifier/RFC5280/URIConstraints.swift
Since Musl is sufficiently different from Glibc (see https://wiki.musl-libc.org/functional-differences-from-glibc.html), it requires a different import, which now should be applied to files that have `import Glibc` in them.
=> Add support for Musl libc

Sources/X509/CertificateSerialNumber.swift, Sources/X509/X509BaseTypes/ECDSASignature.swift, Tests/X509Tests/CertificateTests.swift
`Certificate.SerialNumber` can now be constructed from `FixedWidthInteger` and `StaticBigInt`
=> Add integer initialisers on `Certificate.SerialNumber`

Sources/X509/OCSP/OCSPPolicy.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift
A concrete `OCSPRequester` might want to decided that a request failure is fatal and therefore fail the OCSP verification.
Instead of throwing let the query method return a more descriptor return value that can disambiguate between terminal and non-terminal errors.
`OCSPRequester` can now result in a verification failure
=> Allow `OCSPRequester` to fail `OCSPVerifierPolicy`

Sources/X509/Signature.swift
We only use symbols from `_CryptoExtras` in this file.
This silences the `@preconcurrency import` warning.
=> Remove unused import

IntegrationTests/tests_01_allocation_counters/test_01_resources/run-swift-certificates-alloc-counter-tests.sh, IntegrationTests/tests_01_allocation_counters/test_01_resources/shared.swift, IntegrationTests/tests_01_allocation_counters/test_01_resources/test_parse_webpki_roots.swift, IntegrationTests/tests_01_allocation_counters/test_01_resources/test_validation.swift, docker/docker-compose.2204.57.yaml, docker/docker-compose.2204.58.yaml, docker/docker-compose.2204.59.yaml, docker/docker-compose.2204.main.yaml
This ports a couple of our verifications tests over to our allocation integration test suite.
=> Add `Verifier` allocation tests

Sources/X509/RDNAttribute.swift, Tests/X509Tests/DistinguishedNameTests.swift, docker/docker-compose.2204.57.yaml, docker/docker-compose.2204.58.yaml, docker/docker-compose.2204.59.yaml, docker/docker-compose.2204.main.yaml
Hashing a `RDN.Attribute.Value.utf8String` currently serialises the string to a temporary `Array`. This more than doubles allocations done during verification (allocation test not yet merged: https://github.com/apple/swift-certificates/pull/111)
Implement a  `String.ASN1UTF8StringView` that supports lazy iteration of the DER encoded bytes.
Allocations are reduce from ~1590 to ~660 in the allocation test introduced in #111 
`RDN.Attribute.Value.printable` will follow in a separate PR.
=> Make hashing a `RDN.Attribute.Value.utf8String` not allocate

Sources/X509/Verifier/VerificationDiagnostic.swift
`debugDescription` name and documentation is confusing and should be changed but it is today expected to be suitable to be used as part of a structured display e.g. to be printed as part of `struct` or `enum` with associated values. Therefore it should have no unpaired parentheses, no unescaped quotes and no top-level commas.
- let `debugDescription` simply contain the same contents as `description` but suitable for structural display as described above.
- add a new `multilineDescription` which contains the same contents as the `description` but breaded down on multiple lines for better readability.
`VerificationDiagnostic` has proper string representation suitable for being displayed in an `Array`, as the property of a `struct` or an associated value of an `enum`.
=> Make `debugDescription` work well as part of a structural display

Sources/X509/CMakeLists.txt, Sources/X509/Verifier/RFC5280/RFC5280Policy.swift, Sources/X509/Verifier/RFC5280/VersionPolicy.swift, Tests/X509Tests/RFC5280PolicyTests.swift
v1 certificates do not support extensions and any v1 certificate we encounter with extensions can’t be used to verify a chain.
=> Reject `v1` `Certificate`s with extensions

Sources/X509/Verifier/RFC5280/BasicConstraintsPolicy.swift, Tests/X509Tests/RFC5280PolicyTests.swift
Only non-self-issued certificates count against the maxPathLength limit.
RFC Section 4.2.1.9.  Basic Constraints:
> The pathLenConstraint field is meaningful only if the cA boolean is
> asserted and the key usage extension, if present, asserts the
> keyCertSign bit (Section 4.2.1.3).  In this case, it gives the
> maximum number of non-self-issued intermediate certificates that may
> follow this certificate in a valid certification path.  (Note: The
> last certificate in the certification path is not an intermediate
> certificate, and is not included in this limit.  Usually, the last
> certificate is an end entity certificate, but it can be a CA
> certificate.)  A pathLenConstraint of zero indicates that no non-
> self-issued intermediate CA certificates may follow in a valid
> …
=> Do not count self-issued certificates against maxPathLength

Tests/X509Tests/ExtendedKeyUsageTests.swift, Tests/X509Tests/ExtensionBuilderTests.swift, Tests/X509Tests/PolicyBuilderTests.swift
We have used `ASN1ObjectIdentifier` with just one component in tests but they need at least two components. `swift-asn1` has recently changed the initialiser to enforce this during initialisation time if initialised from a literal. Therefore our tests currently crash.
This PR changes all of our test `ASN1ObjectIdentifier`s to have at least two components.
Tests no longer crash
=> Use valid `ASN1ObjectIdentifier` in tests with at least two components

Sources/X509/Verifier/Verifier.swift, Tests/X509Tests/VerifierTests.swift
We prefer issuers that have a subject key identifier that matches the authority key identifier of the certificate for which were are searching for an issuer. However, currently we have flipped this sort order.
- Flip preference order
- update test
- add test which would previously fail
We actually prefer certificates in the order described above. 
Note that this is just a performance improvement.
=> Fix preference of root certificates

Sources/X509/CertificatePublicKey.swift
Motivation:
PublicKey doesn't conform to DERImplicitlyTaggable which was an oversight during development.
Modifications:
Add conformance to DERImplicitlyTaggable, PEMSerializable, and PEMParsable.
Result:
PublicKey is DERImplicitlyTaggable.
=> Make PublicKey DERImplicitlyTaggable

Sources/X509/CertificatePrivateKey.swift, Sources/X509/CertificatePublicKey.swift, Tests/X509Tests/CertificateTests.swift
and update `Certificate.PublicKey` description to disambiguate from private keys.
=> Add `Certificate.PrivateKey` description

Sources/X509/CertificatePrivateKey.swift, Sources/X509/Extension Types/NameConstraints.swift, Sources/X509/ExtensionsBuilder.swift, Sources/X509/OCSP/OCSPPolicy.swift, Sources/X509/Verifier/Verifier.swift, Sources/X509/X509BaseTypes/TimeCalculations.swift, Tests/CertificateInternalsTests/TinyArrayTests.swift, Tests/X509Tests/OCSPTests.swift
Fix some typos in `Sources` and `Tests`
Note: There is a complete mix of British vs American English spelling of (re/de)serialize vs serialise, but I refrain from changing those.
=> Fix typos in Sources and Tests

Sources/X509/CryptographicMessageSyntax/CMSOperations.swift, Tests/X509Tests/CMSTests.swift
The CMS validation functions should have the diagnostic callback exposed.
=> Add the `diagnosticCallback` to `CMS.isValidSignature`

README.md
It is now included in the official docs: https://github.com/ordo-one/package-benchmark/commit/070dee37abe72c0a3d7e0feff5dca3effd66b541
=> Remove Xcode specific benchmark documentation

README.md
I think we can remove that note now that the library has 1.0.0 tag.
=> Remove note from README about API instability

.swift-format
No code change. We already followed these rules.
=> Align `swift-format` configuration with other projects

Package.swift, Sources/X509/CMakeLists.txt, Sources/X509/CryptographicMessageSyntax/CMSAttribute.swift, Sources/X509/CryptographicMessageSyntax/CMSContentInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSEncapsulatedContentInfo.swift, Sources/X509/CryptographicMessageSyntax/CMSOperations.swift, Sources/X509/CryptographicMessageSyntax/CMSSignature.swift, Sources/X509/CryptographicMessageSyntax/CMSSignedData.swift, Sources/X509/CryptographicMessageSyntax/CMSSignerIdentifier.swift, Sources/X509/CryptographicMessageSyntax/CMSSignerInfo.swift, Sources/X509/X509BaseTypes/AlgorithmIdentifier.swift, Tests/X509Tests/CMSTests.swift
* Support BER Encoded CMS
* Support Attached CMS
* Support Signed Attributes CMS
=> Add Expanded CMS Support

CMakeLists.txt
Swift currently requires 3.19.x to build.  Bump the CMake minimum version to 3.19 to allow us to remove some workarounds from earlier releases.
=> build: simplify build rules (NFC)

Sources/X509/RDNAttribute.swift, Tests/X509Tests/DistinguishedNameTests.swift
Motivation
RDNAttribute Values are mostly strings, and it's useful to be able to convert them. This patch adds that support.
Modifications
Add support for converting RDN attribute values into Strings.
Result
Easier to work with distinguished names.
=> Support converting RDNAttribute values into Strings

CMakeLists.txt
With this tweak, we should be able to build the package in debug mode even on Windows. We always use the release mode DLL form of the C/C++ runtime on Windows and can build the Swift code in Debug or Release mode optimizations.
=> build: support building in Debug mode on Windows

Sources/X509/CryptographicMessageSyntax/CMSSignature.swift, Sources/X509/OCSP/OCSPPolicy.swift, Sources/_CertificateInternals/_TinyArray.swift, Tests/CertificateInternalsTests/TinyArrayTests.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift
Nightly compilers start complaining about retroactive conformances.
- move conformance to declaring module
- optimise code to not allocate
- add tests
no warning. optimal generated code for:
```swift
func foo1(int: Int) -> _TinyArray<Int> {
[int]
}
```
which now compiles down to:
```
output.foo1(int: Swift.Int) -> output._TinyArray<Swift.Int>:
mov     rax, rdi
xor     edx, edx
ret
```
(only with nightly compiler)
https://godbolt.org/z/a91fPe6or
=> Move `ExpressibleByArrayLiteral` conformance of `_TinyArray` to the declaring module

Sources/X509/RDNAttribute.swift, Tests/X509Tests/DistinguishedNameTests.swift
The 1.1.0 release included a patch (#154) that supported converting RDNAttribute values into strings. This patch missed that the `.any` case may also have strings in it.
While investigating this limitation, @Lukasa  realised that the constructor function was excessively complex. While it attempted to coerce based on extra information in the ASN.1 specification, it always fell back into the `.any` case. This meant that as a practical matter we always took the same few paths, and so could safely simplify the code.
- Simplify DER decoding of RDNAttribute.Values
- Normalise internal storage to guarantee that `.any` can never contain bytes which are equal to the DER representation of `.printable` or `.utf8`.
- The above invariant allows us to use the synthesised Hashable implementation which …
=> Simplify the internal representation of `RDN.Attribute.Value`

Tests/X509Tests/CertificateTests.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift, Tests/X509Tests/PEMTests.swift, Tests/X509Tests/VerifierTests.swift
Some of the test code was missing availability guards for Apple platforms, resulting in build failures for these platforms, e.g.
```
error: 'init(pemDocument:)' is only available in iOS 14 or newer
let privateKeyAfterRoundtrip = try Certificate.PrivateKey(pemDocument: privateKey.serializeAsPEM())
```
Add missing availability guards. I've tried to keep them as scoped as possible. Some of the tests rely on initializers in `CryptoKit` that are only available since iOS 14. One suite of tests used this so extensively that I made the whole suite only available on newer platforms.
Tests can now build and run on iOS and other Apple platforms.
=> Add missing availability guards in tests

CMakeLists.txt
When building swift-crypto outside of the toolchain (e.g. to build LSP), it is convenient to support vendoring dependencies.  Add support for falling back to local builds of the dependencies when not provided as an existing build.
=> build: add support to vendor dependencies

Sources/X509/DistinguishedNameBuilder/CountryName.swift, Tests/X509Tests/DistinguishedNameBuilderTests.swift, Tests/X509Tests/DistinguishedNameTests.swift
We currently encode CountryName as `UTF8String` when converted to a `RelativeDistinguishedName.Attribute`.
However, the X.520 says that it should be a `PrintableString` instead:
```
countryName ATTRIBUTE ::= {
SUBTYPE OF name
WITH SYNTAX CountryName
SINGLE VALUE TRUE
LDAP-SYNTAX countryString.&id
LDAP-NAME {"c"}
ID id-at-countryName }
CountryName ::= PrintableString(SIZE (2)) (CONSTRAINED BY { -- ISO 3166 alpha-2 codes only -- })
```
This PR changes `CountryName` to be encoded as a `PrintableString` instead.
=> CountryName should be a PrintableString RDNA

Tests/X509Tests/CSRTests.swift
This test no longer passes with Swift Crypto main, as it relies on RSA 1024 which we now forbid
=> Remove now-breaking test vector test

Tests/X509Tests/CertificateTests.swift
=> Make `testCertificateDescription` independent of system date formatting settings

Sources/X509/Verifier/ServerIdentityPolicy.swift, Tests/X509Tests/ServerIdentityPolicyTests.swift
=> Use case-insensitive comparison when validating cert domain name

Sources/X509/Verifier/AllOfPolicies.swift, Sources/X509/Verifier/OneOfPolicies.swift, Tests/X509Tests/PolicyBuilderTests.swift
This matches what verifier does (https://github.com/apple/swift-certificates/blob/83640c8097acaec17c9835a083e89678cb0f2b66/Sources/X509/Verifier/Verifier.swift#L22) and allows users to more easily use policies which throw in their initialiser
=> Allow OneOfPolicies and AllOfPolicies to take throwing policy builders, to match Verifier

Sources/X509/Verifier/ServerIdentityPolicy.swift
Fixes the following errors:
```
D:\swift-certificates\Sources\X509\Verifier\ServerIdentityPolicy.swift:78:17: error: cannot find type 'in_addr' in scope
case v4(in_addr)
^~~~~~~
D:\swift-certificates\Sources\X509\Verifier\ServerIdentityPolicy.swift:79:17: error: cannot find type 'in6_addr' in scope
case v6(in6_addr)
^~~~~~~~
D:\swift-certificates\Sources\X509\Verifier\ServerIdentityPolicy.swift:144:64: error: cannot find type 'in_addr' in scope
public static func parsingIPv4Address(_ string: String) -> in_addr? {
^~~~~~~
D:\swift-certificates\Sources\X509\Verifier\ServerIdentityPolicy.swift:157:64: error: cannot find type 'in6_addr' in scope
...
```
=> Add missing import statement for Windows.

Sources/X509/CryptographicMessageSyntax/CMSOperations.swift, Sources/X509/CryptographicMessageSyntax/CMSSignerInfo.swift, Tests/X509Tests/CMSTests.swift
Motivation:
Many CMS signing validations require the inclusion of signing time in signedAttrs (for example Apple Wallet's Pass CMS signing validation)
Modifications:
* Adds optional includeSigningTime flag to CMS.sign method (defaults to false)
* When includeSigningTime flag is true: includes signing-time (UTCTime ASN1Type), content-type, and message-digest signedAttrs and signs those instead of content bytes (as specified in RFC 5652 section 5.4)
* Adds contentType ASN1ObjectIdentifier
* Adds CMSSigningError (noTimeZone, invalidSigningDateComponent) for when includeSigningTime is true and unable to get UTC time zone or date components
* Adds tests for valid and invalid CMS signature when including signedAttrs
Result:
Providing the includeSigningTime = true flag to CMS.sign will cause …
=> Adds support for including signing time in signedAttrs for CMS signing.

Sources/X509/Certificate.swift, Sources/X509/Docs.docc/Creating Certificates.md, Tests/X509Tests/CertificateDERTests.swift
Currently, there is no way to create an instance of `Certificate` from `Security.SecCertificate` and vice versa (GitHub Issue #168).
- Added an initializer to `Certificate` which constructs an instance from `Security.SecCertificate`.
- Added a static function `createWithCertificate(_ certificate: Certificate)` in an extension to `Security.SecCertificate` which returns a `SecCertificate` instance.
- Various errors when trying to add an initializer in an extension of `Security.SecCertificate` -- this is presumably because `SecCertificate` is defined in C.
Users can create an instance of `Certificate` from `Security.SecCertificate` and vice versa.
=> Add bridge between `Certificate` and `Security.SecCertificate`

Tests/X509Tests/CMSTests.swift, Tests/X509Tests/OCSPPolicyVerifierTests.swift, Tests/X509Tests/ServerIdentityPolicyTests.swift
Motivation:
This is consistent with what underlying assert does. Swift 6 warns about this mismatch
Modifications:
Use filePath for test assert location
Result:
Consistency in test assert location reportin
=> Use filePath for test assert location

Sources/X509/Verifier/RFC5280/URIConstraints.swift
Tested natively on Android AArch64 with a recent trunk Swift toolchain, no problems.
=> Add support for Android

Sources/X509/SecKeyWrapper.swift, Tests/X509Tests/SecKeyWrapperTests.swift
It seems that `kSecAttrKeyTypeECDSA` is not available on non-mac platforms. This patch amends the code to run appropriately on those platforms.
I've validated this works by testing in the iOS simulator. I'll need to validate the other platforms as well, but that'll take a little while longer, so I'll make a follow-up patch if this turns out to be insufficient.
Resolves #202.
=> Avoid the macOS requirement.

Sources/X509/CMakeLists.txt, Sources/X509/CertificatePrivateKey.swift, Sources/X509/CertificatePublicKey.swift, Sources/X509/Curve25519+DER.swift, Sources/X509/Digests.swift, Sources/X509/PKCS8PrivateKey.swift, Sources/X509/Signature.swift, Sources/X509/SignatureAlgorithm.swift, Sources/X509/X509BaseTypes/AlgorithmIdentifier.swift, Sources/_CertificateInternals/CMakeLists.txt, Tests/X509Tests/CertificateTests.swift, Tests/X509Tests/SignatureTests.swift
Motivation
While Ed25519 is not available in the WebPKI, there are a number of contexts where it's an appropriate signature algorithm for X.509. In those contexts,
we should allow the signature algorithm.
Modifications
Add support for Ed25519 keys and signatures.
Add unit tests
Result
Ed25519 support in the X509 certs
=> Add support for Ed25519 certificates

Package.swift, Tests/X509Tests/ExtendedKeyUsageTests.swift, Tests/X509Tests/ExtensionBuilderTests.swift
Enable MemberImportVisibility check on all targets. Use a standard string header and footer to bracket the new block for ease of updating in the future with scripts.
=> Enable MemberImportVisibility check on all targets

.github/workflows/main.yml, .github/workflows/pull_request.yml, Package.swift, README.md, Sources/X509/SecKeyWrapper.swift, Tests/X509Tests/SecKeyWrapperTests.swift, Tests/X509Tests/SignatureTests.swift
Motivation:
To catch potential data races at build time.
Modifications:
- Bump Swift tools version from 5.8 to 5.9 in Package.swift.
- Enable strict concurrency in Package.swift.
- Adjust the documentation section on the supported Swift versions.
- Implement minor fixes for the surfaced strict concurrency warnings.
- Add `-require-explicit-sendable` to the 6.0, nightly 6.0 and nightly main CI checks.
Result:
Strict concurrency adoption.
=> Enable strict concurrency

Sources/X509/RDNAttribute.swift, Tests/X509Tests/DistinguishedNameTests.swift
Some certificate authorities issue certificates with invalid RDN attribute values. Certificates must use UTF8String instead of PrintableString to represent strings that contains `*` or `@`, but mistakes happen.
When a RDN attribute value is a PrintableString or UTF8String with an invalid content, rather than rejecting the certificate, fall back to storing the value as an Any.
Certificate authorities using the wrong string type is a common mistake. For example, DigiCert issued intermediate certificates with invalid ampersands to Wells Fargo & Company (golang/go#22970). 
This PR adds *partial* support for certificates that contain invalid PrintableString or UTF8String (less likely) values. When failing to parse a PrintableString or UTF8String, the raw bytes are stored as an Any (same as …
=> Support certificates with invalid RDN attribute values

Tests/X509Tests/IPAddressTests.swift
Following on https://github.com/apple/swift-certificates/pull/183 and https://github.com/apple/swift-certificates/pull/207, we need to `import Android` in `IPAddressTests.swift` to get `inet_pton` and `in6_addr`.
With this addition, tests pass on Android again.
=> Add Android import for IPAddressNameTests

Sources/X509/CryptographicMessageSyntax/CMSSignerIdentifier.swift, Tests/X509Tests/CMSTests.swift
As pointed out in https://github.com/apple/swift-certificates/issues/203, the SignerIdentifier in PKCS#7 CMS should be implicitly tagged while the currently swift-certificates explicitly tags it. This PR contains changes for SignerIdentifier of SubjectKeyIdentifier type to be implicitly tagged.
[RFC 5652 § 12.1](https://datatracker.ietf.org/doc/html/rfc5652#section-12.1):
```
SignerIdentifier ::= CHOICE {
issuerAndSerialNumber IssuerAndSerialNumber,
subjectKeyIdentifier [0] SubjectKeyIdentifier }
```
Resolves: https://github.com/apple/swift-certificates/issues/203
=> Tag CMS signer identifier implicitly

Sources/X509/CryptographicMessageSyntax/CMSOperations.swift, Sources/X509/Digests.swift, Tests/X509Tests/CMSTests.swift
Per [RFC 5652 § 11.2](https://datatracker.ietf.org/doc/html/rfc5652#section-11.2):
"For signed-data, the message digest is computed using the signer's message digest algorithm."
Currently, when computing the signed attributes' message digest, `CMS.sign` assumes the digest algorithm is SHA256, which is incorrect. The behavior of `CMS.isValid` is already correct and doesn't need updating. I've made `Digest` conform to `Sequence` to facilitate the conversion/comparison of the message digest.
=> Use proper hash when computing message digest in signed attributes

Sources/X509/X509BaseTypes/AlgorithmIdentifier.swift
This PR adds missing cases and fixes a small typo.
I haven't added tests, as `AlgorithmIdentifier` is internal API.
=> Fix a small error in AlgorithmIdentifier description and add missing cases

.github/workflows/pull_request.yml
Warnings as errors is enabled on 5.9, but this is preventing us from adding visionOS as a platform in our availability guards. Since we're not regressing anything by doing this, and we're close to dropping support for 5.9 anyways, we should remove this setting so that we can support visionOS.
=> Remove warnings as errors from 5.9 CI

.github/workflows/main.yml
See https://github.com/apple/swift-certificates/pull/243
=> Remove warnings as errors from 5.9 main runs

Sources/X509/CertificatePrivateKey.swift, Tests/X509Tests/CertificateDERTests.swift
This PR adds a new `init(derBytes:)` to initialise a private key in PKCS8 format from an array of DER bytes.
=> Add new `Certificate.PrivateKey` init from PKCS8 DER bytes

Tests/X509Tests/CertificateTests.swift
Base on `macOS 11 and iOS 14 (iPadOS 14)`, I think the correct is `macCatalyst 14` . Maybe it is a copy issue above available condition in this file `@available(macOS 13.3, iOS 16.4, watchOS 9.4, tvOS 16.4, macCatalyst 16.4, visionOS 1.0, *)` .
=> Correct macCatalyst 14 in CertificateTests.swift

CMakeLists.txt, cmake/modules/SwiftSupport.cmake
Teach the CMake build to install swiftmodules using the full module triple. This uses the compiler to determine the appropriate module triple instead of attempting to compute the architecture in CMake script, making the build more robust for new platforms and architectures.
Also removing redundant policies. CMP0077 and CMP0091 were added before the minimum CMake version and therefore will always be active in this project.
=> CMake: Use full module triples

Sources/X509/Lock.swift
Much like OpenBSD, the FreeBSD pthread APIs are not imported with the appropriate nullability annotations, so the base pthread mutex type should be an optional value. Eventually we should provide API notes to fix this issue, but that is not in place today.
See https://github.com/swiftlang/swift/issues/81407
=> Fix pthread use on FreeBSD

Sources/X509/CMakeLists.txt, Sources/X509/Verifier/CertificateStore.swift, Sources/X509/Verifier/CustomCertificateStore.swift, Sources/X509/Verifier/Verifier.swift, Tests/X509Tests/CertificateStore.swift
This change adds support for implementing a `CustomCertificateStore` in a backwards compatible way with minimal impact to performance. A custom certificate store can be implemented, and then the new `CertificateStore(custom:)` constructor can be used so that the custom certificate store can be used interchangeably with a "normal" certificate store.
Additionally, a test case verifies that this new protocol will work for our use case. More specifically, the use case we have is for normalization of distinguished names so that an exact match of distinguished names is no longer required. For example, if `printableString` should be used interchangeably with a `utf8String`.
This pull request has two commits:
- One that adds support for a `CustomCertificateStore`
- One that modifies the …
=> Custom certificate store

Sources/X509/CertificatePrivateKey.swift, Sources/X509/Signature.swift, Tests/X509Tests/SignatureTests.swift
This PR introduces two key changes to improve flexibility when working with signatures in swift-certificates. Previously, it was only possible to verify signatures using `Certificate.PrivateKey`, but not to generate them.
- The internal `sign(bytes:signatureAlgorithm:)` method on `Certificate.PrivateKey` is now public, allowing users to generate signatures directly.
- `Certificate.Signature` gains a new `rawRepresentation` property that exposes the raw byte representation of a signature.
=> Support singing via Certificate PrivateKey

Sources/X509/Lock.swift
Much like OpenBSD, the FreeBSD pthread APIs are not imported with the appropriate nullability annotations, so the base pthread mutex type should be an optional value. Eventually we should provide API notes to fix this issue, but that is not in place today.
See https://github.com/swiftlang/swift/issues/81407
(cherry picked from commit 9d7ff7720ed0c8573409ca4081834d4c8aaf3c7d)
=> [1.10.x] Fix pthread use on FreeBSD (#253)

.github/workflows/main.yml, .github/workflows/pull_request.yml, Benchmarks/Thresholds/6.2/CertificatesBenchmark.Parse_WebPKI_Roots_from_DER.p90.json, Benchmarks/Thresholds/6.2/CertificatesBenchmark.Parse_WebPKI_Roots_from_PEM_files.p90.json, Benchmarks/Thresholds/6.2/CertificatesBenchmark.Parse_WebPKI_Roots_from_multi_PEM_file.p90.json, Benchmarks/Thresholds/6.2/CertificatesBenchmark.TinyArray.append.p90.json, Benchmarks/Thresholds/6.2/CertificatesBenchmark.TinyArray_non-allocating_functions.p90.json, Benchmarks/Thresholds/6.2/CertificatesBenchmark.Verifier.p90.json
Motivation:
Swift 6.2 has been released, we should add it to our CI coverage.
Modifications:
Add additional Swift 6.2 jobs where appropriate in main.yml, pull_request.yml
Result:
Improved test coverage.
=> Enable Swift 6.2 jobs in CI
